package com.Wsdl2Code.WebServices.Service;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 3/21/2014 5:15:46 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.Wsdl2Code.WebServices.Service.VectorClasse;
import com.Wsdl2Code.WebServices.Service.VectorCours;
import com.Wsdl2Code.WebServices.Service.VectorIntervenant;
import com.Wsdl2Code.WebServices.Service.VectorModule;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class ScheduleInfo implements KvmSerializable {
    
    public VectorClasse allClassesField;
    public VectorCours allCours;
    public VectorIntervenant allIntervenants;
    public VectorModule allModules;
    
    public ScheduleInfo(){}
    
    public ScheduleInfo(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("AllClasses"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("AllClasses");
            allClassesField = new VectorClasse(j);
        }
        if (soapObject.hasProperty("AllCours"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("AllCours");
            allCours = new VectorCours(j);
        }
        if (soapObject.hasProperty("AllIntervenants"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("AllIntervenants");
            allIntervenants = new VectorIntervenant(j);
        }
        if (soapObject.hasProperty("AllModules"))
        {
            SoapObject j = (SoapObject)soapObject.getProperty("AllModules");
            allModules = new VectorModule(j);
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return allClassesField;
            case 1:
                return allCours;
            case 2:
                return allIntervenants;
            case 3:
                return allModules;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 4;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "AllClasses";
                break;
            case 1:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "AllCours";
                break;
            case 2:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "AllIntervenants";
                break;
            case 3:
                info.type = PropertyInfo.VECTOR_CLASS;
                info.name = "AllModules";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
