package com.Wsdl2Code.WebServices.Service;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 3/21/2014 5:15:46 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class ScheduleEntity implements KvmSerializable {
    
    public int eventId;
    public String day;
    public String date;
    public String period;
    public String moduleId;
    public String courseId;
    public String room;
    public String teacherId;
    public String classIdField;
    public int weekNumber;
    
    public ScheduleEntity(){}
    
    public ScheduleEntity(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("EventId"))
        {
            Object obj = soapObject.getProperty("EventId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                eventId = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                eventId = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("Day"))
        {
            Object obj = soapObject.getProperty("Day");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                day = j.toString();
            }else if (obj!= null && obj instanceof String){
                day = (String) obj;
            }
        }
        if (soapObject.hasProperty("Date"))
        {
            Object obj = soapObject.getProperty("Date");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                date = j.toString();
            }else if (obj!= null && obj instanceof String){
                date = (String) obj;
            }
        }
        if (soapObject.hasProperty("Period"))
        {
            Object obj = soapObject.getProperty("Period");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                period = j.toString();
            }else if (obj!= null && obj instanceof String){
                period = (String) obj;
            }
        }
        if (soapObject.hasProperty("ModuleId"))
        {
            Object obj = soapObject.getProperty("ModuleId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                moduleId = j.toString();
            }else if (obj!= null && obj instanceof String){
                moduleId = (String) obj;
            }
        }
        if (soapObject.hasProperty("CourseId"))
        {
            Object obj = soapObject.getProperty("CourseId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                courseId = j.toString();
            }else if (obj!= null && obj instanceof String){
                courseId = (String) obj;
            }
        }
        if (soapObject.hasProperty("Room"))
        {
            Object obj = soapObject.getProperty("Room");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                room = j.toString();
            }else if (obj!= null && obj instanceof String){
                room = (String) obj;
            }
        }
        if (soapObject.hasProperty("TeacherId"))
        {
            Object obj = soapObject.getProperty("TeacherId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                teacherId = j.toString();
            }else if (obj!= null && obj instanceof String){
                teacherId = (String) obj;
            }
        }
        if (soapObject.hasProperty("ClassId"))
        {
            Object obj = soapObject.getProperty("ClassId");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                classIdField = j.toString();
            }else if (obj!= null && obj instanceof String){
                classIdField = (String) obj;
            }
        }
        if (soapObject.hasProperty("WeekNumber"))
        {
            Object obj = soapObject.getProperty("WeekNumber");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                weekNumber = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                weekNumber = (Integer) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return eventId;
            case 1:
                return day;
            case 2:
                return date;
            case 3:
                return period;
            case 4:
                return moduleId;
            case 5:
                return courseId;
            case 6:
                return room;
            case 7:
                return teacherId;
            case 8:
                return classIdField;
            case 9:
                return weekNumber;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 10;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "EventId";
                break;
            case 1:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Day";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Date";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Period";
                break;
            case 4:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ModuleId";
                break;
            case 5:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "CourseId";
                break;
            case 6:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "Room";
                break;
            case 7:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "TeacherId";
                break;
            case 8:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "ClassId";
                break;
            case 9:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "WeekNumber";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
    /**
     * Rend les informations d'un horaire.
     * @return Les informations d'horaire légèrement mises en page
     */
    public String toString(){
    	StringBuilder sb = new StringBuilder();
    	sb.append(this.courseId + " - ");
    	sb.append(this.room + "\n");
    	sb.append(this.teacherId);
    	return sb.toString();
    }
}
