package com.Wsdl2Code.WebServices.Service;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 3/21/2014 5:15:46 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import com.Wsdl2Code.WebServices.Service.WS_Enums.*;
import java.util.List;
import org.ksoap2.SoapEnvelope;
import org.ksoap2.SoapFault;
import org.ksoap2.serialization.SoapSerializationEnvelope;
import org.ksoap2.transport.HttpTransportSE;
import org.ksoap2.HeaderProperty;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import android.os.AsyncTask;
import org.ksoap2.serialization.MarshalFloat;

public class Service {
    
    public String NAMESPACE ="http://heig-vd.ch/Schemas/ComemSchedule/";
    public String url="http://services.heig-vd.ch/ComemSchedule/Service.asmx";
    public int timeOut = 60000;
    public IWsdl2CodeEvents eventHandler;
    public SoapProtocolVersion soapVersion;
    
    public Service(){}
    
    public Service(IWsdl2CodeEvents eventHandler)
    {
        this.eventHandler = eventHandler;
    }
    public Service(IWsdl2CodeEvents eventHandler,String url)
    {
        this.eventHandler = eventHandler;
        this.url = url;
    }
    public Service(IWsdl2CodeEvents eventHandler,String url,int timeOutInSeconds)
    {
        this.eventHandler = eventHandler;
        this.url = url;
        this.setTimeOut(timeOutInSeconds);
    }
    public void setTimeOut(int seconds){
        this.timeOut = seconds * 1000;
    }
    public void setUrl(String url){
        this.url = url;
    }
    public void GetScheduleAsync(RequestEntity request) throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        GetScheduleAsync(request, null);
    }
    
    public void GetScheduleAsync(final RequestEntity request,final List<HeaderProperty> headers) throws Exception{
        
        new AsyncTask<Void, Void, VectorScheduleEntity>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected VectorScheduleEntity doInBackground(Void... params) {
                return GetSchedule(request, headers);
            }
            @Override
            protected void onPostExecute(VectorScheduleEntity result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("GetSchedule", result);
                }
            }
        }.execute();
    }
    
    public VectorScheduleEntity GetSchedule(RequestEntity request){
        return GetSchedule(request, null);
    }
    
    public VectorScheduleEntity GetSchedule(RequestEntity request,List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("http://heig-vd.ch/Schemas/ComemSchedule/","GetSchedule");
        soapEnvelope.addMapping("http://heig-vd.ch/Schemas/ComemSchedule/","request",new RequestEntity().getClass());
        soapReq.addProperty("request",request);
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("http://heig-vd.ch/Schemas/ComemSchedule/GetSchedule", soapEnvelope,headers);
            }else{
                httpTransport.call("http://heig-vd.ch/Schemas/ComemSchedule/GetSchedule", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    VectorScheduleEntity resultVariable = new VectorScheduleEntity(j);
                    return resultVariable;
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }
    
    public void GetScheduleInfoAsync() throws Exception{
        if (this.eventHandler == null)
            throw new Exception("Async Methods Requires IWsdl2CodeEvents");
        GetScheduleInfoAsync(null);
    }
    
    public void GetScheduleInfoAsync(final List<HeaderProperty> headers) throws Exception{
        
        new AsyncTask<Void, Void, ScheduleInfo>(){
            @Override
            protected void onPreExecute() {
                eventHandler.Wsdl2CodeStartedRequest();
            };
            @Override
            protected ScheduleInfo doInBackground(Void... params) {
                return GetScheduleInfo(headers);
            }
            @Override
            protected void onPostExecute(ScheduleInfo result)
            {
                eventHandler.Wsdl2CodeEndedRequest();
                if (result != null){
                    eventHandler.Wsdl2CodeFinished("GetScheduleInfo", result);
                }
            }
        }.execute();
    }
    
    public ScheduleInfo GetScheduleInfo(){
        return GetScheduleInfo(null);
    }
    
    public ScheduleInfo GetScheduleInfo(List<HeaderProperty> headers){
        SoapSerializationEnvelope soapEnvelope = new SoapSerializationEnvelope(SoapEnvelope.VER11);
        soapEnvelope.implicitTypes = true;
        soapEnvelope.dotNet = true;
        SoapObject soapReq = new SoapObject("http://heig-vd.ch/Schemas/ComemSchedule/","GetScheduleInfo");
        soapEnvelope.setOutputSoapObject(soapReq);
        HttpTransportSE httpTransport = new HttpTransportSE(url,timeOut);
        try{
            if (headers!=null){
                httpTransport.call("http://heig-vd.ch/Schemas/ComemSchedule/GetScheduleInfo", soapEnvelope,headers);
            }else{
                httpTransport.call("http://heig-vd.ch/Schemas/ComemSchedule/GetScheduleInfo", soapEnvelope);
            }
            Object retObj = soapEnvelope.bodyIn;
            if (retObj instanceof SoapFault){
                SoapFault fault = (SoapFault)retObj;
                Exception ex = new Exception(fault.faultstring);
                if (eventHandler != null)
                    eventHandler.Wsdl2CodeFinishedWithException(ex);
            }else{
                SoapObject result=(SoapObject)retObj;
                if (result.getPropertyCount() > 0){
                    Object obj = result.getProperty(0);
                    SoapObject j = (SoapObject)obj;
                    ScheduleInfo resultVariable =  new ScheduleInfo (j);
                    return resultVariable;
                    
                }
            }
        }catch (Exception e) {
            if (eventHandler != null)
                eventHandler.Wsdl2CodeFinishedWithException(e);
            e.printStackTrace();
        }
        return null;
    }
    
}
